spring:
  kafka:
    bootstrap-servers:
      - localhost:9092
    streams:
      state-dir: /Users/krishnakumar.m/Desktop/personal/github/kafka-projects/kafka-streams/state-store-dir

server:
  port: 8082

default:
  deserialization:
    exception:
      handler: true

stethoscope:
  clients:
    - applicationName: order-service
      sourceTopic: "order.service.heartbeat"
      sinkTopic: "order.service.evicted.instances"
logging:
  level:
    org.apache.kafka: INFO
