spring:
  kafka:
    bootstrap-servers:
      - localhost:9092
    streams:
      state-dir: /Users/krishnakumar.m/Desktop/personal/github/kafka-projects/kafka-streams/state-store-dir

server:
  port: 8082

default:
  deserialization:
    exception:
      handler: true

stethoscope:
  clients:
    instance-eviction-info:
      - application-name: order-service
        window-duration-seconds: 3600
        grace-duration-seconds: 0
        sink-topic: "order.service.evicted.instances"
      - application-name: orderbox
        window-duration-seconds: 3600
        grace-duration-seconds: 0
        sink-topic: "orderbox.evicted.instances"
logging:
  level:
    org.apache.kafka: INFO
