spring:
  kafka:
    bootstrap-servers:
      - localhost:9092
    streams:
      state-dir: /Users/krishnakumar.m/Desktop/personal/github/kafka-projects/kafka-streams/state-store-dir

server:
  port: 8082

default:
  deserialization:
    exception:
      handler: true

stethoscope:
  clients:
    instanceEvictionInfo:
      - applicationName: order-service
        windowDurationSeconds: 3600
        graceDurationSeconds: 0
        sinkTopic: "order.service.evicted.instances"
logging:
  level:
    org.apache.kafka: INFO
