spring:
  application:
    name: stethoscope

stethoscope:
  clients:
    evaluate-client-liveness-settings:
      - application-name: order-service
        window-duration-seconds: 3600
        grace-duration-seconds: 0
        sink-topic: "orderService.deadInstances"
      - application-name: payment-service
        window-duration-seconds: 3600
        grace-duration-seconds: 0
        sink-topic: "paymentService.deadInstances"
